import db from "../db/connection.js"
import Post from "../models/post.js"

db.on('error', console.error.bind(console, 'MongoDB connection error:'))

const main = async () => {
    const posts = [
        { name: 'Benny', content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."},
        { name: 'Claire', content: "Duis at consectetur lorem donec massa sapien faucibus et molestie. Tristique senectus et netus et malesuada fames. Maecenas sed enim ut sem viverra. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Venenatis lectus magna fringilla urna porttitor rhoncus. Tellus cras adipiscing enim eu turpis. Nisi lacus sed viverra tellus in hac habitasse. Purus sit amet volutpat consequat mauris. Ac turpis egestas integer eget aliquet. Mauris vitae ultricies leo integer malesuada nunc vel risus. Viverra vitae congue eu consequat ac felis. Commodo elit at imperdiet dui accumsan. Egestas egestas fringilla phasellus faucibus."},
        { name: 'Joey', content: "Egestas congue quisque egestas diam in arcu. In aliquam sem fringilla ut. Nulla facilisi nullam vehicula ipsum a arcu. Egestas sed sed risus pretium quam vulputate dignissim. Aliquet bibendum enim facilisis gravida neque convallis. Mattis molestie a iaculis at erat. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Vitae proin sagittis nisl rhoncus mattis. Dolor morbi non arcu risus quis. Ultricies integer quis auctor elit sed vulputate. Vel fringilla est ullamcorper eget. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Ornare aenean euismod elementum nisi."},
        { name: 'Abe', content: "Nec ultrices dui sapien eget. Purus sit amet luctus venenatis. Viverra suspendisse potenti nullam ac. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Non consectetur a erat nam at lectus urna duis. Tortor id aliquet lectus proin nibh nisl condimentum. Tempor id eu nisl nunc mi ipsum faucibus vitae. Fringilla est ullamcorper eget nulla facilisi. Rhoncus dolor purus non enim praesent. Ut lectus arcu bibendum at varius vel pharetra vel turpis. Maecenas sed enim ut sem. Neque viverra justo nec ultrices dui. Ornare lectus sit amet est placerat in egestas. Lectus nulla at volutpat diam ut venenatis tellus. Tincidunt dui ut ornare lectus sit amet est placerat."},
        { name: 'Sunny', content: "Porttitor rhoncus dolor purus non enim praesent. Cursus euismod quis viverra nibh. Proin fermentum leo vel orci porta non pulvinar. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Integer enim neque volutpat ac tincidunt vitae semper quis. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Eget nullam non nisi est sit amet facilisis magna. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Volutpat maecenas volutpat blandit aliquam etiam. A scelerisque purus semper eget. Fringilla ut morbi tincidunt augue interdum. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Tortor aliquam nulla facilisi cras fermentum odio. A cras semper auctor neque vitae. Tristique nulla aliquet enim tortor at auctor."},
        { name: 'Lizzy', content: "Volutpat odio facilisis mauris sit amet massa vitae. Ultrices dui sapien eget mi proin sed. Turpis tincidunt id aliquet risus. Lorem ipsum dolor sit amet. Et odio pellentesque diam volutpat. Mattis rhoncus urna neque viverra justo. Aenean sed adipiscing diam donec adipiscing tristique risus. Massa tincidunt dui ut ornare. Augue ut lectus arcu bibendum at varius. Dui ut ornare lectus sit. Nisl suscipit adipiscing bibendum est ultricies. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Maecenas accumsan lacus vel facilisis volutpat est. In metus vulputate eu scelerisque felis imperdiet proin fermentum."},
        { name: 'Julie', content: "Ac ut consequat semper viverra nam libero justo laoreet sit. Et magnis dis parturient montes nascetur ridiculus mus. Ut placerat orci nulla pellentesque dignissim enim sit amet. Vulputate mi sit amet mauris commodo quis imperdiet. At auctor urna nunc id cursus. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Pellentesque id nibh tortor id aliquet lectus proin. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Amet consectetur adipiscing elit ut. Pulvinar sapien et ligula ullamcorper malesuada proin. Malesuada proin libero nunc consequat interdum varius sit amet. Amet est placerat in egestas erat imperdiet sed. Ac odio tempor orci dapibus ultrices. Feugiat scelerisque varius morbi enim nunc faucibus a. Faucibus pulvinar elementum integer enim neque volutpat ac. Et molestie ac feugiat sed lectus vestibulum. Semper eget duis at tellus at urna condimentum."}
    ]

    await Post.insertMany(posts)
    console.log("Created posts!")
}

const run = async () => {
    await main()
    db.close()
}

run()